version: '3.7'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NETWORK_URL=http://ganache:8545
      - MONITOR_CHECK_INTERVAL_MS=10000
      - MAX_WAIT_TIME_MS=300000
      - RPC_PORT=8080
    depends_on:
      - ganache
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: ganache-cli -h 0.0.0.0
